# Generated by Django 3.2.21 on 2023-09-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180724_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple choice', 'Multiple Choice: Multiple answers'), ('single choice', 'Multiple Choice: Single answer'), ('short text', 'Short Text'), ('long text', 'Long Text')], max_length=256),
        ),
    ]
