# Generated by Django 4.2.13 on 2024-06-07 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystate',
            name='submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
