# Generated by Django 3.2.25 on 2024-06-07 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_activitystate_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystate',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
