# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carr_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlashVideoBlock',
        ),
        migrations.DeleteModel(
            name='PullQuoteBlock_2',
        ),
        migrations.DeleteModel(
            name='PullQuoteBlock_3',
        ),
    ]
