# Generated by Django 3.2.21 on 2023-09-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_bruise_recon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/img//%Y/%m/%d/', verbose_name='image'),
        ),
    ]
